### ISSUE TITLE
Incompatible with GooglePlayResolver (External Dependency Manager)

### ISSUE THREAD

**Issue by newatlanta19006** [Unity-Technologies/com.unity.mobile.notifications#44]
Because you now have .java files directly in this package. External Dependency Manager will not detect duplicate uses and the build will have issues due to conflicting api functions. 

The Resolver is pretty much essential in any project so support should be prioritized. 

I dont think there is a work around currently that I know of so I am downgrading to a previous version.

**Comment by jounisuom** [comment]
I also have this issue because the AndroidNotificationPostProcessor adds the com.android.support:appcompat-v7:27.1.1 dependency to the project. Namely I get this error:

`
java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (:androidx.core.core-1.2.0:) and classes.jar (com.android.support:support-compat:27.1.1)
`

I can't get rid of it because the dependency is always added.

We are also forced to use older version.

I suggest the following fix:
- remove the aforementioned dependency from the post-processor
- in java files, refactor android.support.annotation.Keep to androidx.annotation.Keep

**Comment by vincent-unity** [comment]
Fixed in the new patch release 1.2.1-preview.
